apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  annotations:
    btrfs-provisioner.timo.schwarzer.dev/node: k3d-k3s-default-agent-0
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: btrfs-provisioner
  resources:
    requests:
      storage: 10Gi