apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: btrfs-provisioner-k3d-k3s-default-agent-0
  resources:
    requests:
      storage: 10Gi