apiVersion: v1
kind: Namespace
metadata:
  name: btrfs-provisioner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: btrfs-provisioner
  name: btrfs-provisioner-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: btrfs-provisioner-role
rules:
- apiGroups: [ "" ]
  resources: [ "nodes", "persistentvolumeclaims", "configmaps" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "endpoints", "persistentvolumes", "pods" ]
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources: [ "events" ]
  verbs: [ "create", "patch" ]
- apiGroups: [ "storage.k8s.io" ]
  resources: [ "storageclasses" ]
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: btrfs-provisioner-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: btrfs-provisioner-role
subjects:
- kind: ServiceAccount
  name: btrfs-provisioner-service-account
  namespace: btrfs-provisioner